//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technicise.ShabdoKhoj.DbInteract
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechniciseShabdoKhojEntities : DbContext
    {
        public TechniciseShabdoKhojEntities()
            : base("name=TechniciseShabdoKhojEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_File_Tags> T_File_Tags { get; set; }
        public virtual DbSet<T_File_Twt> T_File_Twt { get; set; }
        public virtual DbSet<T_Indexing_Queue> T_Indexing_Queue { get; set; }
    }
}
