//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technicise.ShabdoKhoj.DbInteract
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_File_Twt
    {
        public System.Guid file_id_fk { get; set; }
        public string file_twt { get; set; }
    }
}
