//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technicise.ShabdoKhoj.DbInteract
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Indexing_Queue
    {
        public System.Guid file_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public Nullable<int> index_status { get; set; }
        public Nullable<System.DateTime> time_added { get; set; }
    }
}
